// <auto-generated />
using System;
using Kafka.CassandraConsumer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kafka.CassandraConsumer.Migrations
{
    [DbContext(typeof(HelloContext))]
    partial class HelloContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Kafka.CassandraConsumer.Models.HelloEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("HelloEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
